services:
  httpd:
    platform: linux/amd64
    build: ./.github/scripts
    ports:
      - 8080:80
    volumes:
      - ./mount:/etc/httpd/mount:rw
    # - ./modules:/etc/httpd/modules:ro
    #environment:
      # - ENV_VAR=value
    #env_file:
    #  - httpd.env
    networks:
      - backend

networks:
  backend:
