#on: [push, pull_request]
name: CI
#on: pull_request
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          repository: AndreiMartinencoTR/repo_to_test_action
          ref: main
      
      # - name: Read the README
      #   run: |
      #     ls -la
      #     cat ./README.md
      #     ls -la
      - name: See what is inside
        run: |
          ls -la
          mkdir ./mount
          cp -r ./somefolder ./mount
          ls -la ./mount/     

      # - name: Check Apache syntax
      #   id: check_syntax_result
      #   uses: AndreiMartinencoTR/check_apache_syntax@v1

      # - name: checkout
      #   uses: actions/checkout@v3
      - name: Run docker compose
        run: |
          action_script_bash=".github/scripts/action_script.sh"
          if [ ! -f "$action_script_bash" ]
          then
            echo "ERROR - There is no $action_script_bash"
          else
            bash $action_script_bash
          fi

      - name: Check for errors
        run: |
          error_output_file="./mount/error.txt"
          syntax_check=$(tail -1 $error_output_file | grep -q "Syntax OK")
          syntax_check_result=$?
          if [ ! $syntax_check_result == 0 ]
          then
            tail -40 $error_output_file
            exit 1
          fi 
      
      # - name: Create mnt folder
      #   run: |
      #     mkdir ./mnt
      #     cp README.md ./mnt



      # - name: Check Apache syntax
      #   id: script_result
      #   uses: AndreiMartinencoTR/check_apache_syntax@v1
        
        #with:
        #  branch-name: ${{ github.head_ref }}
      
      
      # - name: List the content
      #   run: |
      #     ls -la
      #     cat results.txt


      # - name: Branch name
      #   run: echo running on branch ${{ github.head_ref }}
      # - name: Check Apache syntax
      #   id: script_result
      #   uses: AndreiMartinencoTR/check_apache_syntax@v1
      #   with:
      #     branch-name: ${{ github.head_ref }}
      # - name: Get the output branch
      #   run: echo "The output from the script ${{ steps.script_result.outputs.result }}"
