#on: [push, pull_request]
name: CI
on: pull_request
#on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
<<<<<<< HEAD
          repository: AndreiMartinencoTR/repo_to_test_action
          ref: some_branch

      # - name: Branch name
      #   run: echo running on branch ${{ github.head_ref }}
      # - name: Check Apache syntax
      #   id: script_result
      #   uses: AndreiMartinencoTR/check_apache_syntax@v1
      #   with:
      #     branch-name: ${{ github.head_ref }}
      # - name: Get the output branch
      #   run: echo "The output from the script ${{ steps.script_result.outputs.result }}"
=======
          branch-name: ${{ github.head_ref }}
      - name: Get the output branch
        run: echo "The output from the script ${{ steps.script_result.outputs.result }}"
>>>>>>> 788140487f047d9ed085cc69c84bee15d866652c
